### ISSUE TITLE
Invite creation CRUD in the dashboard

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#13]

**Comment by cryptix** [comment]
I will start with the [community mode of joining](https://github.com/ssb-ngi-pointer/rooms2/blob/4915c544a5bf902aff0dc449151424591180ec04/docs/Participation/Joining.md#L1) since we don't have the different modes yet. Restricting form there based on user roles later seems to make the most sense for me.

* [ ] add _create invite_ button
  * [ ] HTTP endpoint
  * [ ] outline `admindb.InviteService` and SQLite schema
  * [ ] dashboard link
  * [ ] _here is your invite_ HTML template
  * [ ] also as JSON for better App integration
* [ ] add _consume_ endpoint
  * [ ] HTTP endpoint
  * [ ] update active invite token (possible with the public key of the consumee so that the invite creator can follow/allow them)
  * [ ] returns the [tunnel address](https://github.com/ssb-ngi-pointer/rooms2/blob/4915c544a5bf902aff0dc449151424591180ec04/docs/Participation/Tunnel%20addresses.md)
  * [ ] either as a HTML page or ssb-uri redirect depending on the request

**Comment by staltz** [comment]
Is this done? It seems done

**Comment by cryptix** [comment]
Indeed!
