### ISSUE TITLE
alias URL should be stable when visited

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#152]
Visiting `alice.room.com` should not redirect to (i.e. change the browser's address bar) `room.com/aliases/alice`, it should stay on `alice.room.com` to allow copy-pasting it.

**Comment by cryptix** [comment]
cc #117

**Comment by cryptix** [comment]
I agree but shouldn't we expand this to generate the right URL scheme?

I'd really like to support the Tor hidden-service scheme where wildcard domains are not possible.

**Comment by staltz** [comment]
I agree with that, but isn't it a separate issue? (Or separate in the sense that it could be done later, and that there are different strategies how to support Tor hidden-service)

**Comment by cryptix** [comment]
True, just related because you mentioned copy and paste and for me the first step is copying it from somewhere.


I just had a shower thought to fix the issue on nginx. Instead of URL rewrite, which by all accounts is not possible when changing the domain, we could have a 2nd proxy_pass just for the aliases.
