### ISSUE TITLE
muxrpc errors in client-initiated sign-in with SSB

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#170]
I got this in manyverse, which caused the app to crash. (Yes, I thought SIWSSB was 100% done)

What's strange is that the crash doesn't give a JS stack trace, it usually does. Also, `muxrpc: session terminated` doesn't seem to come from JS (it seems to come from go-ssb-room) because I searched the JS code (it's one huge file, when bundled) for that string and nothing came up.

```
2021-04-20T14:53:56.724Z ssb:http-auth:client requestSolution where sid=@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519, cid=@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519, sc=kbqNkBrTg_wGRRgmtFHZBQ6I1m-GyOt1xCd-kwP0cbk=, cc=TgIlmXfVitZUVwX3NPKiWUvkLs3QZZ+kRGYg7VIKYys=
2021-04-20T14:53:56.756Z ssb:http-auth:client requestSolution where sid=@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519, cid=@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519, sc=5AUBOw5hG0p7AjL5Q3VgR0j86AfX9BaTNYDnoV_xIcs=, cc=TgIlmXfVitZUVwX3NPKiWUvkLs3QZZ+kRGYg7VIKYys=
{ name: 'Error', message: 'muxrpc: session terminated', stack: '' }
```

What's weird about the logs above is that `requestSolution` happens twice it seems.

The hermies.club website showed (in HTML):

```
Error #500 Internal Server Error

ssb http auth: could not request solution from client: muxrpc(httpAuth.requestSolution): 
did not receive data for request: muxrpc: session terminated
```

**Comment by staltz** [comment]
I tried again, and it worked, but I noticed that `ssb:http-auth:client requestSolution` is logged twice. The log comes from [ssb-http-auth-client](https://github.com/ssb-ngi-pointer/ssb-http-auth-client/blob/9e8ca67505cffe05aeedb2a2fe00f96826d19327/src/plugin-http-auth.ts#L41) which is only when `httpAuth.requestSolution` is being answered, so its odd that it's being called twice. Note that the 2nd call has a different `sc` than 1st call. This is true for both failing cases and success cases, so it may hint towards where the problem is.

**Comment by cryptix** [comment]
`muxrpc: session terminated` is definitely a go-muxrpc thing. It _only_ happens when the connection is about to be closed (stop reading incoming muxrpc events due to a fatal error) and used as the `EndErr` body for still open requests.

What i dont get is why it crashes the JS side. It's an error on a stream like any other. There might be a glitch that it is sent on streams which shouldn't be closed/error'ed on? Like, already answered/closed request streams (async calls are still "streams", just that they only contain a single message).

I haven't managed to capture this throw/crash in a nodejs test yet but I'd be totally down to pair on this tomorrow.

**Comment by cryptix** [comment]
I don't have an explanation for the double `requestSolution` call. There is no retry logic on the server side there.

**Comment by staltz** [comment]
Couldn't reproduce this issue anymore. :tada:
