### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by cblgh** [ssb-ngi-pointer/go-ssb-room#203]
To enable people's easy use of go-ssb-room, I think it would be a good idea to create at least a couple [releases](https://github.com/ssb-ngi-pointer/go-ssb-room/releases).

We can [go fancy](https://goreleaser.com/), or we can [go basic](https://github.com/cblgh/lieu/blob/main/release.sh). What matters is there are some nice binaries for folx to play with :3

**Comment by cryptix** [comment]
Because of #79 we need to build these on each target platform individually.

I propose to initially make one per the big linuxes (debian, ubuntu, archlinux, ..?) and then collect package files. Using goreleaser might help with the bundling process of how to actually construct the different package files.

Not sure if people really need this on macOS or windows even tho it's possible to build.

**Comment by cryptix** [comment]
Follow up issue: update the docs and READMEs to reflect this install path (right now we just have _build from source_).

**Comment by cryptix** [comment]
We have v2.0.5 out now!
